<?xml version="1.0" ?>

<robot name="robo" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="camera_length" value="0.1" />
    <xacro:property name="camera_radius" value="0.05" />

    <link name="camera_link">
        <visual>
            <geometry>
                <cylinder radius="${camera_radius}" length="${camera_length}" />
            </geometry>
            <origin xyz="0 0 ${camera_length / 2}"  rpy="0 0 0"/>
            <material name="blue" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${camera_radius}" length="${camera_length}" />
            </geometry>
            <origin xyz="0 0 ${camera_length / 2}"  rpy="0 0 0"/>
        </collision>
        <xacro:cylinder_inertia m="0.8" r="${2*camera_radius}" l="${2*camera_length}"
                                 xyz="0 0 ${camera_length / 2}" rpy="0 0 0" />
        </link>
    
    <joint name="base_camera_joint" type="fixed">
        <parent link="base_link" />
        <child link="camera_link" />
        <origin xyz="${base_length / 4} 0 ${base_height}" rpy="0 0 0" />
        <!-- <axis xyz="0 0 1" />
        <limit lower="-3.14" upper="3.14" velocity="100" effort="100" /> -->
    </joint>

    <gazebo reference="camera_link">
        <material>Gazebo/Blue</material>
        <sensor name="camera_sensor" type="camera">
            <pose>0 0 0 0 0 0</pose>
            <visualize>true</visualize>
            <update_rate>20.0</update_rate>
            <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
                <frame_name>camera_link</frame_name>
            </plugin>
        </sensor>
    </gazebo>

</robot>